Add owner display name to jtx contract
bitfireAT/ical4android pull request #84
Opened 2023-02-22 14:31 UTC by sunkup

This is to provide the owner display name in a jtx collection.
Reference to davx5 issue: https://github.com/bitfireAT/davx5/issues/219
Refernce to davx5 branch: https://github.com/bitfireAT/davx5/tree/219-provide-owner-for-task-providers-again

2023-02-22 15:00 UTC, patrickunterwegs requested changes
Hey @sunkup , please don't change the contract, the source of truth must remain in jtx Board ! 😉
If you could provide the owner URL and display name in an object that is passed to the method from the screenshot in the ticket, I'll take care of the rest!

2023-02-22 16:21 UTC, sunkup commented
> method from the screenshot in the ticket, I'll take care of the rest

You lost me there. What ticket? Which Screenshot? :sweat_smile:

2023-02-22 16:25 UTC, closed without merging

2023-02-22 16:34 UTC, patrickunterwegs commented
Ah, sorry, I was actually meaning the screenshot in the comment that obviously isn't visible for you 😁

![Screenshot_20230221_192047_GitHub.jpg](https://user-images.githubusercontent.com/72232737/220693864-21cbc18e-c1e7-44d1-8257-798e0b635287.jpg)

That's the comment there!

2023-02-22 16:56 UTC, sunkup commented
> Hey @sunkup , please don't change the contract, the source of truth must remain in jtx Board ! wink If you could provide the owner URL and display name in an object that is passed to the method from the screenshot in the ticket, I'll take care of the rest!

AFAIK, I can only pass a String value for the `JtxContract.JtxCollection.OWNER` key (as defined in `JtxContract`). The other keys are all of primitive types too. How would I pass an object? Do you want me to serialize it? If so, in which format?

Am I missing something obvious here?

2023-02-22 21:44 UTC, patrickunterwegs commented
> > Hey @sunkup , please don't change the contract, the source of truth must remain in jtx Board ! wink If you could provide the owner URL and display name in an object that is passed to the method from the screenshot in the ticket, I'll take care of the rest!
> 
> AFAIK, I can only pass a String value for the `JtxContract.JtxCollection.OWNER` key (as defined in `JtxContract`). The other keys are all of primitive types too. How would I pass an object? Do you want me to serialize it? If so, in which format?
> 
> > Ah, sorry, I was actually meaning the screenshot in the comment that obviously isn't visible for you grin
> 
> Also, why is it not visible to me? I can not see your comment either. Does this have to do [with this](https://github.com/bitfireAT/davx5/issues/219#issuecomment-1439751881) ?
> 
> Feels like I am missing out on some information obvious here, haha.

I really don't know why the comment stays hidden for you...
About the change: I didn't mean to pass an object to JtxContract.JtxCollection.OWNER, but somehow the owner display name or owner URL should be passed to the whole class. Once this is done, I can take over and make sure the owner is passed to the right field. 
The more important challenge here is how to get the owner information into the LocalJtxCollection...?

2023-02-23 08:45 UTC, sunkup commented
> About the change: I didn't mean to pass an object to JtxContract.JtxCollection.OWNER, but somehow the owner display name or owner URL should be passed to the whole class. Once this is done, I can take over and make sure the owner is passed to the right field. The more important challenge here is how to get the owner information into the LocalJtxCollection...?

I have taken care of that already [in the commit](https://github.com/bitfireAT/davx5/pull/221/commits/0ba8a2881586dfde46054b2ca4548e0e3dc245d4) in the [draft pr for the original issue](https://github.com/bitfireAT/davx5/pull/221) ;)

You can just [continue here](https://github.com/bitfireAT/davx5/pull/221/commits/0ba8a2881586dfde46054b2ca4548e0e3dc245d4#r1115376105), the owner is available already :)